### ISSUE TITLE
add "juju-dev" image to list of available images

### ISSUE THREAD

**Issue by sed-i** [canonical/multipass-workflows#4]
**What are you trying to do?**
It would be nice to be able to launch (disposable) instances of juju and related tools needed for charm development.
Launching an instance and installing all the tools takes quite some time.

**What's your proposed solution?**
Have an official "juju-dev" image with microk8s and charmcraft.
MicroK8s should ideally be set up per https://juju.is/docs/sdk/dev-setup 

**Additional context**
NTA.

**Comment by sed-i** [comment]
@Saviq, launching a workflow would re-run the commands every time, correct?
Is there a way to take the result of a workflow and turn it into an image? Just to save time on snap install etc.

**Comment by sed-i** [comment]
@Saviq How can I test locally my draft #5 ?

**Comment by Saviq** [comment]
@sed-i you can override the systemd service like so:

```ini
# /etc/systemd/system/snap.multipass.multipassd.service.d/override.conf
[Service]
Environment="MULTIPASS_WORKFLOWS_URL=https://github.com/sed-i/multipass-workflows/archive/refs/heads/charm-dev.zip"
```

**Comment by sed-i** [comment]
Is there a way to see stdout/stderr of the commands in the runcmd section?
I am using `multipass launch -vvvv` and all I see is "Waiting for initialization to complete".

**Comment by Saviq** [comment]
> Is there a way to see stdout/stderr of the commands in the runcmd section?

When you see "Waiting...", you can interrupt that and `multipass shell …`, and inside see `/var/log/cloud-init*`.
